# Generate boot-to-Talos user data
echo "ðŸ“ Generating boot-to-Talos user data..."
cat > boot-to-talos-userdata.yaml << EOF
#cloud-config
write_files:
- path: /opt/boot-to-talos.sh
  permissions: '0755'
  content: |
    #!/bin/bash
    set -euo pipefail
    echo "ðŸš€ Starting boot-to-Talos transition..."
    
    # Install Docker for image operations
    apt-get update
    apt-get install -y docker.io
    systemctl start docker
    
    # Configure Docker to use registry caches (critical - no direct internet from private subnets)
    mkdir -p /etc/docker
    cat > /etc/docker/daemon.json << 'DOCKER_EOF'
    {
      "registry-mirrors": ["http://${REGISTRY_CACHE}"],
      "insecure-registries": ["${REGISTRY_CACHE}"]
    }
    DOCKER_EOF
    systemctl restart docker
    
    # Pull custom Talos image via GHCR registry cache (port 5054)
    echo "ðŸ“¦ Pulling custom Talos image via bastion cache: ${REGISTRY_CACHE}"
    echo "ðŸ” Image: ${CUSTOM_TALOS_IMAGE}"
    
    # Direct pull from cache (nodes have no direct internet - critical)
    docker pull "${REGISTRY_CACHE}/urmanac/cozystack-assets/talos:demo-stable"
    
    # Tag as if from original registry for easier handling
    docker tag "${REGISTRY_CACHE}/urmanac/cozystack-assets/talos:demo-stable" "${CUSTOM_TALOS_IMAGE}"
    
    # Extract Talos installer for kexec transition
    echo "ðŸ”„ Extracting Talos installer..."
    docker create --name talos-extract "${CUSTOM_TALOS_IMAGE}"
    mkdir -p /opt/talos-installer
    docker cp talos-extract:/assets/talos/arm64/boot/ /opt/talos-installer/ 2>/dev/null || {
      echo "âš ï¸  Boot assets not in expected location, trying alternative paths..."
      docker cp talos-extract:/usr/install/arm64/ /opt/talos-installer/ 2>/dev/null || {
        echo "ðŸ“‹ Listing available paths in Talos image..."
        docker run --rm "${CUSTOM_TALOS_IMAGE}" find / -name "*vmlinuz*" -o -name "*initramfs*" || true
      }
    }
    docker rm talos-extract
    
    # Transition to Talos (kexec)
    echo "ðŸŽ¯ Transitioning to Talos..."
    # Implementation depends on specific Talos image structure
    # This would invoke kexec with Talos kernel and initramfs
    echo "Boot-to-Talos preparation complete"
