#cloud-config
write_files:
- path: /opt/boot-to-talos.sh
  permissions: '0755'
  content: |
    #!/bin/bash
    set -euo pipefail
    echo "ðŸš€ Starting boot-to-Talos transition..." | tee -a /var/log/boot-to-talos.log
    
    # Install Docker for image operations
    apt-get update | tee -a /var/log/boot-to-talos.log
    apt-get install -y docker.io | tee -a /var/log/boot-to-talos.log
    systemctl start docker | tee -a /var/log/boot-to-talos.log
    
    # Configure Docker to use registry caches
    mkdir -p /etc/docker
    cat > /etc/docker/daemon.json << 'DOCKER_EOF'
    {
      "registry-mirrors": ["http://10.10.1.100:5054"],
      "insecure-registries": ["10.10.1.100:5054"]
    }
    DOCKER_EOF
    systemctl restart docker | tee -a /var/log/boot-to-talos.log
    
    # Test registry connectivity
    echo "ðŸ“¦ Testing registry cache connectivity..." | tee -a /var/log/boot-to-talos.log
    curl -v http://10.10.1.100:5054/v2/ 2>&1 | tee -a /var/log/boot-to-talos.log || true
    
    # Pull custom Talos image via registry cache
    echo "ðŸ” Pulling: ghcr.io/urmanac/cozystack-assets/talos:demo-stable" | tee -a /var/log/boot-to-talos.log
    docker pull "ghcr.io/urmanac/cozystack-assets/talos:demo-stable" 2>&1 | tee -a /var/log/boot-to-talos.log || true
    
    # List what we got
    docker images | tee -a /var/log/boot-to-talos.log
    
    echo "Boot-to-Talos test complete" | tee -a /var/log/boot-to-talos.log

runcmd:
- /opt/boot-to-talos.sh
final_message: "Ubuntu â†’ Talos transition test initiated"
